/**
 * Every lucide glyph the product imports — GENERATED, do not hand-edit.
 *
 * A hand-kept list drifts the moment someone imports a new glyph, and it did: the
 * first version of this page listed 56 of the 152 in use. Regenerate with:
 *
 *   python3 -c "
 *   import re, pathlib
 *   root = pathlib.Path('src')
 *   used = set()
 *   for p in root.rglob('*.tsx'):
 *       for m in re.finditer(r'import\s*\{([^}]*)\}\s*from\s*[\"']lucide-react[\"']', p.read_text(errors='replace'), re.S):
 *           for tok in m.group(1).split(','):
 *               tok = tok.strip()
 *               if tok and not tok.startswith('type'):
 *                   n = tok.split(' as ')[0].strip()
 *                   if n[:1].isupper() and not n.endswith('Icon'): used.add(n)
 *   print(',\n  '.join('\"%s\"' % n for n in sorted(used)))"
 *
 * Names ending in `Icon` are skipped: those are shadcn's internal aliases
 * (PanelLeftIcon, XIcon), not glyphs the product chose.
 */
export const ICONS_IN_USE = [
  "Activity",
  "AlertCircle",
  "AlertTriangle",
  "AlignCenter",
  "AlignLeft",
  "AlignRight",
  "Armchair",
  "ArrowDownRight",
  "ArrowLeft",
  "ArrowRight",
  "ArrowUp",
  "ArrowUpDown",
  "ArrowUpRight",
  "BarChart3",
  "Battery",
  "BatteryCharging",
  "BatteryFull",
  "BatteryLow",
  "BatteryMedium",
  "BatteryWarning",
  "Bed",
  "Bell",
  "Bold",
  "BookOpen",
  "Bot",
  "Boxes",
  "Briefcase",
  "Cake",
  "CalendarClock",
  "CalendarDays",
  "Camera",
  "Car",
  "Cat",
  "Check",
  "CheckCircle2",
  "ChefHat",
  "ChevronDown",
  "ChevronLeft",
  "ChevronRight",
  "ChevronUp",
  "ChevronsUpDown",
  "Circle",
  "CircleDashed",
  "Clock",
  "Cloud",
  "CloudFog",
  "CloudLightning",
  "CloudRain",
  "CloudSnow",
  "CloudSun",
  "Cog",
  "Coins",
  "Container",
  "Copy",
  "Cpu",
  "Disc3",
  "DoorClosed",
  "DoorOpen",
  "Droplet",
  "Equal",
  "ExternalLink",
  "Eye",
  "FileSpreadsheet",
  "Film",
  "Filter",
  "Flame",
  "Flower2",
  "Footprints",
  "Fuel",
  "Gauge",
  "Globe",
  "HardDrive",
  "History",
  "Home",
  "Inbox",
  "Info",
  "KeyRound",
  "Lamp",
  "LampCeiling",
  "LayoutGrid",
  "Lightbulb",
  "ListChecks",
  "Loader2",
  "Lock",
  "LockOpen",
  "LogOut",
  "MapPin",
  "MemoryStick",
  "Minus",
  "Moon",
  "MoreHorizontal",
  "MoreVertical",
  "MoveRight",
  "Network",
  "Package",
  "Palette",
  "PanelTop",
  "Pause",
  "PauseCircle",
  "Pencil",
  "PencilRuler",
  "PiggyBank",
  "Play",
  "Plug",
  "Plus",
  "Power",
  "Printer",
  "Projector",
  "Radio",
  "RefreshCw",
  "Repeat",
  "Router",
  "Search",
  "Server",
  "Shapes",
  "Shield",
  "ShieldAlert",
  "ShieldCheck",
  "ShieldOff",
  "ShoppingBasket",
  "Siren",
  "SlidersHorizontal",
  "Snowflake",
  "Sofa",
  "Sparkles",
  "Speaker",
  "SquareMousePointer",
  "Sun",
  "SunDim",
  "SunMedium",
  "Sunrise",
  "Sunset",
  "Terminal",
  "Thermometer",
  "ThermometerSun",
  "Trash2",
  "TrendingDown",
  "TrendingUp",
  "UploadCloud",
  "User",
  "Users",
  "Utensils",
  "UtensilsCrossed",
  "Volume1",
  "Volume2",
  "Warehouse",
  "WashingMachine",
  "Wifi",
  "WifiOff",
  "Wind",
  "X",
  "Zap",
] as const;
