/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTeslaRouteImport } from './routes/_app.tesla'
import { Route as AppReseauRouteImport } from './routes/_app.reseau'
import { Route as AppBudgetRouteImport } from './routes/_app.budget'
import { Route as AppEnergieIndexRouteImport } from './routes/_app.energie.index'
import { Route as AppBudgetIndexRouteImport } from './routes/_app.budget.index'
import { Route as AppRoomRoomKeyRouteImport } from './routes/_app.room.$roomKey'
import { Route as AppEnergieSaisieRouteImport } from './routes/_app.energie.saisie'
import { Route as AppBudgetMensuelRouteImport } from './routes/_app.budget.mensuel'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeslaRoute = AppTeslaRouteImport.update({
  id: '/tesla',
  path: '/tesla',
  getParentRoute: () => AppRoute,
} as any)
const AppReseauRoute = AppReseauRouteImport.update({
  id: '/reseau',
  path: '/reseau',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetRoute = AppBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AppRoute,
} as any)
const AppEnergieIndexRoute = AppEnergieIndexRouteImport.update({
  id: '/energie/',
  path: '/energie/',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetIndexRoute = AppBudgetIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBudgetRoute,
} as any)
const AppRoomRoomKeyRoute = AppRoomRoomKeyRouteImport.update({
  id: '/room/$roomKey',
  path: '/room/$roomKey',
  getParentRoute: () => AppRoute,
} as any)
const AppEnergieSaisieRoute = AppEnergieSaisieRouteImport.update({
  id: '/energie/saisie',
  path: '/energie/saisie',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetMensuelRoute = AppBudgetMensuelRouteImport.update({
  id: '/mensuel',
  path: '/mensuel',
  getParentRoute: () => AppBudgetRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/budget': typeof AppBudgetRouteWithChildren
  '/reseau': typeof AppReseauRoute
  '/tesla': typeof AppTeslaRoute
  '/budget/mensuel': typeof AppBudgetMensuelRoute
  '/energie/saisie': typeof AppEnergieSaisieRoute
  '/room/$roomKey': typeof AppRoomRoomKeyRoute
  '/budget/': typeof AppBudgetIndexRoute
  '/energie/': typeof AppEnergieIndexRoute
}
export interface FileRoutesByTo {
  '/reseau': typeof AppReseauRoute
  '/tesla': typeof AppTeslaRoute
  '/': typeof AppIndexRoute
  '/budget/mensuel': typeof AppBudgetMensuelRoute
  '/energie/saisie': typeof AppEnergieSaisieRoute
  '/room/$roomKey': typeof AppRoomRoomKeyRoute
  '/budget': typeof AppBudgetIndexRoute
  '/energie': typeof AppEnergieIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/budget': typeof AppBudgetRouteWithChildren
  '/_app/reseau': typeof AppReseauRoute
  '/_app/tesla': typeof AppTeslaRoute
  '/_app/': typeof AppIndexRoute
  '/_app/budget/mensuel': typeof AppBudgetMensuelRoute
  '/_app/energie/saisie': typeof AppEnergieSaisieRoute
  '/_app/room/$roomKey': typeof AppRoomRoomKeyRoute
  '/_app/budget/': typeof AppBudgetIndexRoute
  '/_app/energie/': typeof AppEnergieIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budget'
    | '/reseau'
    | '/tesla'
    | '/budget/mensuel'
    | '/energie/saisie'
    | '/room/$roomKey'
    | '/budget/'
    | '/energie/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/reseau'
    | '/tesla'
    | '/'
    | '/budget/mensuel'
    | '/energie/saisie'
    | '/room/$roomKey'
    | '/budget'
    | '/energie'
  id:
    | '__root__'
    | '/_app'
    | '/_app/budget'
    | '/_app/reseau'
    | '/_app/tesla'
    | '/_app/'
    | '/_app/budget/mensuel'
    | '/_app/energie/saisie'
    | '/_app/room/$roomKey'
    | '/_app/budget/'
    | '/_app/energie/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tesla': {
      id: '/_app/tesla'
      path: '/tesla'
      fullPath: '/tesla'
      preLoaderRoute: typeof AppTeslaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reseau': {
      id: '/_app/reseau'
      path: '/reseau'
      fullPath: '/reseau'
      preLoaderRoute: typeof AppReseauRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budget': {
      id: '/_app/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AppBudgetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/energie/': {
      id: '/_app/energie/'
      path: '/energie'
      fullPath: '/energie/'
      preLoaderRoute: typeof AppEnergieIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budget/': {
      id: '/_app/budget/'
      path: '/'
      fullPath: '/budget/'
      preLoaderRoute: typeof AppBudgetIndexRouteImport
      parentRoute: typeof AppBudgetRoute
    }
    '/_app/room/$roomKey': {
      id: '/_app/room/$roomKey'
      path: '/room/$roomKey'
      fullPath: '/room/$roomKey'
      preLoaderRoute: typeof AppRoomRoomKeyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/energie/saisie': {
      id: '/_app/energie/saisie'
      path: '/energie/saisie'
      fullPath: '/energie/saisie'
      preLoaderRoute: typeof AppEnergieSaisieRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budget/mensuel': {
      id: '/_app/budget/mensuel'
      path: '/mensuel'
      fullPath: '/budget/mensuel'
      preLoaderRoute: typeof AppBudgetMensuelRouteImport
      parentRoute: typeof AppBudgetRoute
    }
  }
}

interface AppBudgetRouteChildren {
  AppBudgetMensuelRoute: typeof AppBudgetMensuelRoute
  AppBudgetIndexRoute: typeof AppBudgetIndexRoute
}

const AppBudgetRouteChildren: AppBudgetRouteChildren = {
  AppBudgetMensuelRoute: AppBudgetMensuelRoute,
  AppBudgetIndexRoute: AppBudgetIndexRoute,
}

const AppBudgetRouteWithChildren = AppBudgetRoute._addFileChildren(
  AppBudgetRouteChildren,
)

interface AppRouteChildren {
  AppBudgetRoute: typeof AppBudgetRouteWithChildren
  AppReseauRoute: typeof AppReseauRoute
  AppTeslaRoute: typeof AppTeslaRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEnergieSaisieRoute: typeof AppEnergieSaisieRoute
  AppRoomRoomKeyRoute: typeof AppRoomRoomKeyRoute
  AppEnergieIndexRoute: typeof AppEnergieIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBudgetRoute: AppBudgetRouteWithChildren,
  AppReseauRoute: AppReseauRoute,
  AppTeslaRoute: AppTeslaRoute,
  AppIndexRoute: AppIndexRoute,
  AppEnergieSaisieRoute: AppEnergieSaisieRoute,
  AppRoomRoomKeyRoute: AppRoomRoomKeyRoute,
  AppEnergieIndexRoute: AppEnergieIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
