/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTeslaRouteImport } from './routes/_app.tesla'
import { Route as AppReseauRouteImport } from './routes/_app.reseau'
import { Route as AppBudgetRouteImport } from './routes/_app.budget'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AppEnergieIndexRouteImport } from './routes/_app.energie.index'
import { Route as AppBudgetIndexRouteImport } from './routes/_app.budget.index'
import { Route as AppRoomRoomKeyRouteImport } from './routes/_app.room.$roomKey'
import { Route as AppEnergieSaisieRouteImport } from './routes/_app.energie.saisie'
import { Route as AppBudgetVueRouteImport } from './routes/_app.budget.vue'
import { Route as AppBudgetTransactionsRouteImport } from './routes/_app.budget.transactions'
import { Route as AppBudgetPlanificationRouteImport } from './routes/_app.budget.planification'
import { Route as AppBudgetMensuelRouteImport } from './routes/_app.budget.mensuel'
import { Route as AppBudgetImportRouteImport } from './routes/_app.budget.import'
import { Route as AppBudgetAnnuelRouteImport } from './routes/_app.budget.annuel'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AppBudgetVueReserveRouteImport } from './routes/_app.budget.vue.reserve'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeslaRoute = AppTeslaRouteImport.update({
  id: '/tesla',
  path: '/tesla',
  getParentRoute: () => AppRoute,
} as any)
const AppReseauRoute = AppReseauRouteImport.update({
  id: '/reseau',
  path: '/reseau',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetRoute = AppBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppEnergieIndexRoute = AppEnergieIndexRouteImport.update({
  id: '/energie/',
  path: '/energie/',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetIndexRoute = AppBudgetIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBudgetRoute,
} as any)
const AppRoomRoomKeyRoute = AppRoomRoomKeyRouteImport.update({
  id: '/room/$roomKey',
  path: '/room/$roomKey',
  getParentRoute: () => AppRoute,
} as any)
const AppEnergieSaisieRoute = AppEnergieSaisieRouteImport.update({
  id: '/energie/saisie',
  path: '/energie/saisie',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetVueRoute = AppBudgetVueRouteImport.update({
  id: '/vue',
  path: '/vue',
  getParentRoute: () => AppBudgetRoute,
} as any)
const AppBudgetTransactionsRoute = AppBudgetTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppBudgetRoute,
} as any)
const AppBudgetPlanificationRoute = AppBudgetPlanificationRouteImport.update({
  id: '/planification',
  path: '/planification',
  getParentRoute: () => AppBudgetRoute,
} as any)
const AppBudgetMensuelRoute = AppBudgetMensuelRouteImport.update({
  id: '/mensuel',
  path: '/mensuel',
  getParentRoute: () => AppBudgetRoute,
} as any)
const AppBudgetImportRoute = AppBudgetImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppBudgetRoute,
} as any)
const AppBudgetAnnuelRoute = AppBudgetAnnuelRouteImport.update({
  id: '/annuel',
  path: '/annuel',
  getParentRoute: () => AppBudgetRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppBudgetVueReserveRoute = AppBudgetVueReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => AppBudgetVueRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/budget': typeof AppBudgetRouteWithChildren
  '/reseau': typeof AppReseauRoute
  '/tesla': typeof AppTeslaRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/budget/annuel': typeof AppBudgetAnnuelRoute
  '/budget/import': typeof AppBudgetImportRoute
  '/budget/mensuel': typeof AppBudgetMensuelRoute
  '/budget/planification': typeof AppBudgetPlanificationRoute
  '/budget/transactions': typeof AppBudgetTransactionsRoute
  '/budget/vue': typeof AppBudgetVueRouteWithChildren
  '/energie/saisie': typeof AppEnergieSaisieRoute
  '/room/$roomKey': typeof AppRoomRoomKeyRoute
  '/budget/': typeof AppBudgetIndexRoute
  '/energie/': typeof AppEnergieIndexRoute
  '/budget/vue/reserve': typeof AppBudgetVueReserveRoute
}
export interface FileRoutesByTo {
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/reseau': typeof AppReseauRoute
  '/tesla': typeof AppTeslaRoute
  '/': typeof AppIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/budget/annuel': typeof AppBudgetAnnuelRoute
  '/budget/import': typeof AppBudgetImportRoute
  '/budget/mensuel': typeof AppBudgetMensuelRoute
  '/budget/planification': typeof AppBudgetPlanificationRoute
  '/budget/transactions': typeof AppBudgetTransactionsRoute
  '/budget/vue': typeof AppBudgetVueRouteWithChildren
  '/energie/saisie': typeof AppEnergieSaisieRoute
  '/room/$roomKey': typeof AppRoomRoomKeyRoute
  '/budget': typeof AppBudgetIndexRoute
  '/energie': typeof AppEnergieIndexRoute
  '/budget/vue/reserve': typeof AppBudgetVueReserveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_app/budget': typeof AppBudgetRouteWithChildren
  '/_app/reseau': typeof AppReseauRoute
  '/_app/tesla': typeof AppTeslaRoute
  '/_app/': typeof AppIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_app/budget/annuel': typeof AppBudgetAnnuelRoute
  '/_app/budget/import': typeof AppBudgetImportRoute
  '/_app/budget/mensuel': typeof AppBudgetMensuelRoute
  '/_app/budget/planification': typeof AppBudgetPlanificationRoute
  '/_app/budget/transactions': typeof AppBudgetTransactionsRoute
  '/_app/budget/vue': typeof AppBudgetVueRouteWithChildren
  '/_app/energie/saisie': typeof AppEnergieSaisieRoute
  '/_app/room/$roomKey': typeof AppRoomRoomKeyRoute
  '/_app/budget/': typeof AppBudgetIndexRoute
  '/_app/energie/': typeof AppEnergieIndexRoute
  '/_app/budget/vue/reserve': typeof AppBudgetVueReserveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/budget'
    | '/reseau'
    | '/tesla'
    | '/.mcp/invoke-tool/$tool'
    | '/budget/annuel'
    | '/budget/import'
    | '/budget/mensuel'
    | '/budget/planification'
    | '/budget/transactions'
    | '/budget/vue'
    | '/energie/saisie'
    | '/room/$roomKey'
    | '/budget/'
    | '/energie/'
    | '/budget/vue/reserve'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/reseau'
    | '/tesla'
    | '/'
    | '/.mcp/invoke-tool/$tool'
    | '/budget/annuel'
    | '/budget/import'
    | '/budget/mensuel'
    | '/budget/planification'
    | '/budget/transactions'
    | '/budget/vue'
    | '/energie/saisie'
    | '/room/$roomKey'
    | '/budget'
    | '/energie'
    | '/budget/vue/reserve'
  id:
    | '__root__'
    | '/_app'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_app/budget'
    | '/_app/reseau'
    | '/_app/tesla'
    | '/_app/'
    | '/.mcp/invoke-tool/$tool'
    | '/_app/budget/annuel'
    | '/_app/budget/import'
    | '/_app/budget/mensuel'
    | '/_app/budget/planification'
    | '/_app/budget/transactions'
    | '/_app/budget/vue'
    | '/_app/energie/saisie'
    | '/_app/room/$roomKey'
    | '/_app/budget/'
    | '/_app/energie/'
    | '/_app/budget/vue/reserve'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tesla': {
      id: '/_app/tesla'
      path: '/tesla'
      fullPath: '/tesla'
      preLoaderRoute: typeof AppTeslaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reseau': {
      id: '/_app/reseau'
      path: '/reseau'
      fullPath: '/reseau'
      preLoaderRoute: typeof AppReseauRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budget': {
      id: '/_app/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AppBudgetRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/energie/': {
      id: '/_app/energie/'
      path: '/energie'
      fullPath: '/energie/'
      preLoaderRoute: typeof AppEnergieIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budget/': {
      id: '/_app/budget/'
      path: '/'
      fullPath: '/budget/'
      preLoaderRoute: typeof AppBudgetIndexRouteImport
      parentRoute: typeof AppBudgetRoute
    }
    '/_app/room/$roomKey': {
      id: '/_app/room/$roomKey'
      path: '/room/$roomKey'
      fullPath: '/room/$roomKey'
      preLoaderRoute: typeof AppRoomRoomKeyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/energie/saisie': {
      id: '/_app/energie/saisie'
      path: '/energie/saisie'
      fullPath: '/energie/saisie'
      preLoaderRoute: typeof AppEnergieSaisieRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budget/vue': {
      id: '/_app/budget/vue'
      path: '/vue'
      fullPath: '/budget/vue'
      preLoaderRoute: typeof AppBudgetVueRouteImport
      parentRoute: typeof AppBudgetRoute
    }
    '/_app/budget/transactions': {
      id: '/_app/budget/transactions'
      path: '/transactions'
      fullPath: '/budget/transactions'
      preLoaderRoute: typeof AppBudgetTransactionsRouteImport
      parentRoute: typeof AppBudgetRoute
    }
    '/_app/budget/planification': {
      id: '/_app/budget/planification'
      path: '/planification'
      fullPath: '/budget/planification'
      preLoaderRoute: typeof AppBudgetPlanificationRouteImport
      parentRoute: typeof AppBudgetRoute
    }
    '/_app/budget/mensuel': {
      id: '/_app/budget/mensuel'
      path: '/mensuel'
      fullPath: '/budget/mensuel'
      preLoaderRoute: typeof AppBudgetMensuelRouteImport
      parentRoute: typeof AppBudgetRoute
    }
    '/_app/budget/import': {
      id: '/_app/budget/import'
      path: '/import'
      fullPath: '/budget/import'
      preLoaderRoute: typeof AppBudgetImportRouteImport
      parentRoute: typeof AppBudgetRoute
    }
    '/_app/budget/annuel': {
      id: '/_app/budget/annuel'
      path: '/annuel'
      fullPath: '/budget/annuel'
      preLoaderRoute: typeof AppBudgetAnnuelRouteImport
      parentRoute: typeof AppBudgetRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/budget/vue/reserve': {
      id: '/_app/budget/vue/reserve'
      path: '/reserve'
      fullPath: '/budget/vue/reserve'
      preLoaderRoute: typeof AppBudgetVueReserveRouteImport
      parentRoute: typeof AppBudgetVueRoute
    }
  }
}

interface AppBudgetVueRouteChildren {
  AppBudgetVueReserveRoute: typeof AppBudgetVueReserveRoute
}

const AppBudgetVueRouteChildren: AppBudgetVueRouteChildren = {
  AppBudgetVueReserveRoute: AppBudgetVueReserveRoute,
}

const AppBudgetVueRouteWithChildren = AppBudgetVueRoute._addFileChildren(
  AppBudgetVueRouteChildren,
)

interface AppBudgetRouteChildren {
  AppBudgetAnnuelRoute: typeof AppBudgetAnnuelRoute
  AppBudgetImportRoute: typeof AppBudgetImportRoute
  AppBudgetMensuelRoute: typeof AppBudgetMensuelRoute
  AppBudgetPlanificationRoute: typeof AppBudgetPlanificationRoute
  AppBudgetTransactionsRoute: typeof AppBudgetTransactionsRoute
  AppBudgetVueRoute: typeof AppBudgetVueRouteWithChildren
  AppBudgetIndexRoute: typeof AppBudgetIndexRoute
}

const AppBudgetRouteChildren: AppBudgetRouteChildren = {
  AppBudgetAnnuelRoute: AppBudgetAnnuelRoute,
  AppBudgetImportRoute: AppBudgetImportRoute,
  AppBudgetMensuelRoute: AppBudgetMensuelRoute,
  AppBudgetPlanificationRoute: AppBudgetPlanificationRoute,
  AppBudgetTransactionsRoute: AppBudgetTransactionsRoute,
  AppBudgetVueRoute: AppBudgetVueRouteWithChildren,
  AppBudgetIndexRoute: AppBudgetIndexRoute,
}

const AppBudgetRouteWithChildren = AppBudgetRoute._addFileChildren(
  AppBudgetRouteChildren,
)

interface AppRouteChildren {
  AppBudgetRoute: typeof AppBudgetRouteWithChildren
  AppReseauRoute: typeof AppReseauRoute
  AppTeslaRoute: typeof AppTeslaRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEnergieSaisieRoute: typeof AppEnergieSaisieRoute
  AppRoomRoomKeyRoute: typeof AppRoomRoomKeyRoute
  AppEnergieIndexRoute: typeof AppEnergieIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBudgetRoute: AppBudgetRouteWithChildren,
  AppReseauRoute: AppReseauRoute,
  AppTeslaRoute: AppTeslaRoute,
  AppIndexRoute: AppIndexRoute,
  AppEnergieSaisieRoute: AppEnergieSaisieRoute,
  AppRoomRoomKeyRoute: AppRoomRoomKeyRoute,
  AppEnergieIndexRoute: AppEnergieIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
